Onboarding
NucleoidJS/nucleoid.com pull request #32
Opened 2023-07-28 11:03 UTC by halilcengel

2023-07-29 07:54 UTC, 322332 approved these changes

2023-07-31 18:50 UTC, canmingir requested changes

2023-07-31 18:50 UTC, canmingir commented on package.json
> +    "@nucleoidjs/synapses": "github:nucleoidjs/synapses",
It should be "@nucleoidjs/synapses": "^1.0.13" instead

2023-07-31 18:50 UTC, canmingir commented on package.json
> +    "@nucleoidjs/webstorage": "github:nucleoidjs/webstorage",
It shouldn't be part of dev deps and its version should be `"^1.0.2"`

2023-07-31 19:54 UTC, durulkoca approved these changes

2023-08-01 09:43 UTC, canmingir approved these changes

2023-08-01 09:46 UTC, merged